
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class Cancellation extends javax.swing.JFrame {

    /**
     * Creates new form Cancellation
     */
    public Cancellation() {
        initComponents();
          GetTicket();
          FcodeTb.setEditable(false);
          DisplayCan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        TIdCb = new javax.swing.JTextField();
        BackBtn = new javax.swing.JButton();
        BookBtn = new javax.swing.JButton();
        ResetBtn = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        CancellationTable = new javax.swing.JTable();
        FcodeTb = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        CDate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel11.setText("Ticket Cancelletion");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 230, 30));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setText("   Ticket Id");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 120, 30));
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel16.setText("  Flight Code");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 130, 30));

        TIdCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TIdCbActionPerformed(evt);
            }
        });
        jPanel4.add(TIdCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 130, 30));

        BackBtn.setBackground(new java.awt.Color(255, 0, 51));
        BackBtn.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        BackBtn.setText("BACK");
        BackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackBtnMouseClicked(evt);
            }
        });
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        jPanel4.add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, 100, -1));

        BookBtn.setBackground(new java.awt.Color(255, 0, 51));
        BookBtn.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        BookBtn.setText("Cancel");
        BookBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookBtnMouseClicked(evt);
            }
        });
        BookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookBtnActionPerformed(evt);
            }
        });
        jPanel4.add(BookBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 100, -1));

        ResetBtn.setBackground(new java.awt.Color(255, 51, 51));
        ResetBtn.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        ResetBtn.setText("RESET");
        ResetBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResetBtnMouseClicked(evt);
            }
        });
        ResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBtnActionPerformed(evt);
            }
        });
        jPanel4.add(ResetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 120, -1));

        jTextField4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 0, 0));
        jTextField4.setText(" Cancellation List");
        jPanel4.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 170, 30));

        CancellationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(CancellationTable);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 1040, 180));
        jPanel4.add(FcodeTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 150, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel1.setText("Flight Code");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 230, 150, -1));

        jPanel2.setBackground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1060, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 40));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel2.setText("SWAIN AIRLINE");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 340, 30));
        jPanel4.add(CDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 260, 130, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackBtnActionPerformed

    private void BookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookBtnActionPerformed

    private void ResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResetBtnActionPerformed

    private void BackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackBtnMouseClicked
          new MainForm().setVisible(true);
          this.dispose(); 
     
    }//GEN-LAST:event_BackBtnMouseClicked
     Connection Con=null;
       PreparedStatement pst=null;
       ResultSet Rs=null,Rs1=null;
       Statement St=null,St1=null; 
    private void GetTicket()
       {
          try{
                Con=DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinedb","root","root");
                St=Con.createStatement();
                String Query="select * from BookingTbl";
                Rs=St.executeQuery(Query);
                while(Rs.next())
                {
                    //int TicketId = 0;
                    int T=Rs.getInt("TicketId");
                   TIdCb.addItem(T);
                }    
              
          }catch(Exception e)
          {
              
          } 
          
       }    
     private void DisplayCan()
      {
           try{
               Con=DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinedb","root","root");
               St=Con.createStatement();
               Rs=St.executeQuery("select * from cancellationTbl");
               CancellationTable.setModel(DbUtils.resultSetToTableModel(Rs));
           }catch(Exception e)
           {
                
           }  
      }  
      int CId=0;
      private void CountCanc()
      {
           try{
               St1=Con.createStatement();
               Rs1=St1.executeQuery("select Max(CancId) from CancellationTbl");
               Rs1.next();
               CId=Rs1.getInt(1)+1;
           }catch(Exception e)
           {
               
           }
          
      }  
       private void GetFCode()
     {
         String Query="select * from  BookingTbl where TicketId ="+TIdCb.getSelectedItem().toString();
         Statement St;
         ResultSet Rs;
         try{
             Con=DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinedb","root","root");
             St=Con.createStatement();
             Rs=St.executeQuery(Query);
             if(Rs.next())
             {
                 FcodeTb.setText(Rs.getString("FlCode"));
                 
             }  
         }catch(Exception e)
         {
             
         } 
         
     } 
      
    
    private void ResetBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetBtnMouseClicked
       
          FcodeTb.setText(" ");
        
    }//GEN-LAST:event_ResetBtnMouseClicked

    private void TIdCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TIdCbActionPerformed
               GetFCode();
    }//GEN-LAST:event_TIdCbActionPerformed
     private void Cancel()
     {       
        
            try{
               Con=DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinedb","root","root");
               String Query="Delete from  BookingTbl where TicketId= "+TIdCb.getSelectedItem();
               Statement Del=Con.createStatement();
               Del.executeUpdate(Query);
              // JOptionPane.showMessageDialog(this,"Flight Deleted.");
              // DisplayFlight();
               
            }catch(Exception e)
            {
               JOptionPane.showMessageDialog(this,e);
            }
         
           
     }    
    private void BookBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookBtnMouseClicked
          if(FcodeTb.getText().isEmpty())
             {
                  JOptionPane.showMessageDialog(this,"Missing InforMation");
                      
             }else{
                    try{
                          CountCanc();
                         
                          Con=DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinedb","root","root");
                          PreparedStatement Add=Con.prepareStatement("insert into CancelletionTbl values(?,?,?,?)");
                          Add.setInt(1,CId);
                          Add.setInt(2,Integer.valueOf(TIdCb.getSelectedItem().toString()));
                          Add.setString(3,FcodeTb.getText());
                          Add.setString(4,CDate.getDate().toString());
                          int row=Add.executeUpdate();
                          JOptionPane.showMessageDialog(this,"Ticket cancelled.");
                          Con.close();
                          Cancel();
                          DisplayCan();
                          GetTicket();
                         // Clear();
                    }catch(Exception e)
                    {
                     JOptionPane.showMessageDialog(this, e);
                    }     
                     
             }  
        
        
    }//GEN-LAST:event_BookBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cancellation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton BookBtn;
    private com.toedter.calendar.JDateChooser CDate;
    private javax.swing.JTable CancellationTable;
    private javax.swing.JTextField FcodeTb;
    private javax.swing.JButton ResetBtn;
    private javax.swing.JTextField TIdCb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
